service: toggl-report

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:*"
      Resource: "*"
  environment:
    STAGE: ${opt:stage, 'dev'}
    SLACK_WEB_HOOK_URL: ${ssm:/toggl-report/${opt:stage, 'dev'}/slack-web-hook-url}
    SLACK_CHANNEL_NAME: ${ssm:/toggl-report/${opt:stage, 'dev'}/slack-channel-name}
    # TOBE: Report per workspace id
    TOGGL_WORKSPACE_ID: ${ssm:/toggl-report/${opt:stage, 'dev'}/toggl-workspace-id}
    TOGGL_API_TOKEN: ${ssm:/toggl-report/toggl-api-token}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

custom:
  defaultStage: dev

functions:
  togglReport:
    handler: bin/main
    timeout: 900
    events:
      - schedule: cron(0 0 * * ? *)
